Note: This project uses 100% synthetic, pseudonymized data for demonstration purposes. No real Personal Identifiable Information (PII) is included in this repository.

In [ ]:
import pandas as pd

# Dataset A: Housing System (The "Clean-ish" Data)
System_a_data = [
    {"unique_id": "H001", "first_name": "Sarah", "surname": "Johnson", "dob": "1985-04-12", "postcode": "S1 4GW", "address": "12 High Street, Sheffield"},
    {"unique_id": "H002", "first_name": "James", "surname": "Smith", "dob": "1990-11-05", "postcode": "S10 2TH", "address": "Flat 4, Oak House, Crookes"},
    {"unique_id": "H003", "first_name": "Mohammad", "surname": "Khan", "dob": "1978-02-20", "postcode": "S9 3LR", "address": "88 Staniforth Road"},
]

# Dataset B: Benefits System ( The "Messy" Data)
# Note the errors: "Sara" (typo), "Jim" (nickname), "Rd" (abbreviation), missing DOB
system_b_data = [
    {"unique_id": "B991", "first_name": "Sara", "surname": "Johnson", "dob": "1985-04-12", "postcode": "S1 4GW", "address": "12 High St"},
    {"unique_id": "B992", "first_name": "Jim", "surname": "Smith", "dob": "1990-11-05", "postcode": "S10 2TH", "address": "Flt 4 Oak Hse"},
    {"unique_id": "B993", "first_name": "Mo", "surname": "Khan", "dob": "1978-02-20", "postcode": "S9 3LR", "address": "88 Staniforth Rd, Attercliffe"},
]

df_sysa = pd.DataFrame(system_a_data)
df_sysb = pd.DataFrame(system_b_data)

print("Data Created Successfully!")
display(df_sysa)
display(df_sysb)

Data Created Successfully!

,unique_id,first_name,surname,dob,postcode,address
0,H001,Sarah,Johnson,1985-04-12,S1 4GW,"12 High Street, Sheffield"
1,H002,James,Smith,1990-11-05,S10 2TH,"Flat 4, Oak House, Crookes"
2,H003,Mohammad,Khan,1978-02-20,S9 3LR,88 Staniforth Road

,unique_id,first_name,surname,dob,postcode,address
0,B991,Sara,Johnson,1985-04-12,S1 4GW,12 High St
1,B992,Jim,Smith,1990-11-05,S10 2TH,Flt 4 Oak Hse
2,B993,Mo,Khan,1978-02-20,S9 3LR,"88 Staniforth Rd, Attercliffe"